
-- Populate user table with hardcoded values --
INSERT INTO users(email, pic, username) VALUES ('bob@ucsc.com', 'https://lh3.googleusercontent.com/a/ALm5wu1BNu38NDJUK7MgGRRr8KQYLZN_PtqAiE9MXRrFJg=s96-c', 'Bob');
INSERT INTO users(email, pic, username) VALUES ('steve@ucsc.com', 'https://lh3.googleusercontent.com/a/ALm5wu2LYxyLQVPRYjO2SJEuz-wYzOulc7Vil4iWVu85=s96-c', 'Steve');
INSERT INTO users(email, pic, username) VALUES ('cahoneydrops@gmail.com', 'https://www.gratefulweb.com/sites/default/files/images/articles/unnamed_1029.jpg', 'The California Honeydrops');
INSERT INTO users(email, pic, username) VALUES ('joepesci@gmail.com', 'https://m.media-amazon.com/images/M/MV5BODA1OTcwMDk4OF5BMl5BanBnXkFtZTgwOTEyMDQ5NjE@._V1_.jpg', 'Joe Pesci');
INSERT INTO users(email, pic, username) VALUES ('alienguy@ucsc.edu', 'https://cdn.mos.cms.futurecdn.net/LsCK8iqF2axWKc5eavenZ8-1200-80.jpg', 'Alien Guy');
INSERT INTO users(email, pic, username) VALUES ('IWishIWasTaylorSwift@gmail.com', 'https://media1.popsugar-assets.com/files/thumbor/hnVKqXE-xPM5bi3w8RQLqFCDw_E/475x60:1974x1559/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2019/09/09/023/n/1922398/9f849ffa5d76e13d154137.01128738_/i/Taylor-Swift.jpg', 'Could be Taylor Swift');
INSERT INTO users(email, pic, username) VALUES ('gregorysmith@gmail.com', 'https://upload.wikimedia.org/wikipedia/commons/c/c2/Glorious-blue-mountain-range.jpg', 'Gregory Smith');
INSERT INTO users(email, pic, username) VALUES ('beachboardwalk@santacruz.org', 'https://www.genetec.com/binaries/content/gallery/genetecweb/graphic-assets/photos/cardimage_santa-cruz-beach.jpg/cardimage_santa-cruz-beach.jpg/genetecweb%3Asmall', 'City of Santa Cruz');
INSERT INTO users(email, pic, username) VALUES ('iLOVEskating@gmail.com', 'https://thumbs.dreamstime.com/z/pair-figure-ice-skates-splash-watercolor-hand-drawn-sketch-vector-illustration-paints-132750305.jpg', 'ice skates');
INSERT INTO users(email, pic, username) VALUES ('newyear2023@gmail.com', 'https://media-cldnry.s-nbcnews.com/image/upload/rockcms/2021-12/ball-drop-main-AW-211216-fb622f.jpg', 'Billy Joe');
INSERT INTO users(email, pic, username) VALUES ('davidthebeachdude@gmail.com', 'https://images.template.net/wp-content/uploads/2016/04/27120651/Beach-Wallpaper.jpg?width=584', 'David Beach');
INSERT INTO users(email, pic, username) VALUES ('santa@ucsc.com', 'https://cdn-icons-png.flaticon.com/512/3723/3723050.png', 'Santa Claus');
INSERT INTO users(email, pic, username) VALUES ('xcrunners@ncaa.org', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrZf_MuC_8L28zdeHmmTsitbycF-tuRPwwBQ&usqp=CAU', 'Random Runner');

-- Populate event table with hardcoded values --
INSERT INTO events(eventname, email, eventdate, eventtime, eventlocation, latitude, longitude, eventdescription) VALUES ('Joe''s Birthday Party', 'joepesci@gmail.com', '2023-05-22', '11:53:00', '7585 Clairemont Mesa Blvd, San Diego, CA 92111', 32.83146441117766, -117.15651937338356, 'Join me in celebrating my 22nd birthday! There will be free pizza and a round of bowling for anybody who brings a gift worth over $200!');
INSERT INTO events(eventname, email, eventdate, eventtime, eventlocation, latitude, longitude, eventdescription) VALUES ('The California Honeydrops at The Catalyst', 'cahoneydrops@gmail.com', '2022-12-03', '21:00:00', '1011 Pacific Ave, Santa Cruz, CA 95060', 36.97135306655091, -122.0259025598089, 'Watch The California Honeydrops perform at The Catalyst in downtown Santa Cruz! Doors open at 8PM, show begins at 9PM. Ages 16+ allowed.');
INSERT INTO events(eventname, email, eventdate, eventtime, eventlocation, latitude, longitude, eventdescription) VALUES ('Storm Area 51', 'alienguy@ucsc.edu', '2019-09-21', '10:00:00', 'Area 51 Alien Center', 36.64379584637324, -116.39599713098066, 'They can''t stop us all. On September 19th, we''re going to raid Area 51. We''ll be meeting at the Alien Center and then going together.');
INSERT INTO events(eventname, email, eventdate, eventtime, eventlocation, latitude, longitude, eventdescription) VALUES ('Taylor Swift | The Eras Tour', 'IWishIWasTaylorSwift@gmail.com', '2023-07-29', '05:00:00', '4900 Marie P DeBartolo Way, Santa Clara, CA 95054', 37.403, 121.970001, 'Come see Taylor Swift perform songs from all of her albums!');
INSERT INTO events(eventname, email, eventdate, eventtime, eventlocation, latitude, longitude, eventdescription) VALUES ('Night Market', 'bob@ucsc.com', '2023-06-30', '06:30:00', '100 SE Alder St Portland, OR 97214', 45.517940521240234, -122.6635513305664, 'The Portland Night Market showcases many unique businesses that call Portland home. Blending food, culture, music, drinks and retail together for an adventurous evening in the Central Eastside. Come meet some of Portland''s best makers and creators.');
INSERT INTO events(eventname, email, eventdate, eventtime, eventlocation, latitude, longitude, eventdescription) VALUES ('NCAA Cross Country Championships', 'xcrunners@ncaa.org', '2023-11-19', '09:20:00', 'Stillwater, Oklahoma', 36.11381149291992, -97.05725860595703, 'Come watch D1 Cross Country athletes across the nation compete!');
INSERT INTO events(eventname, email, eventdate, eventtime, eventlocation, latitude, longitude, eventdescription) VALUES ('Beach Volleyball Tournament', 'davidthebeachdude@gmail.com', '2022-12-15', '01:00:00', 'Waddell Beach, California 95017', 37.095017, -122.2780144, 'Come join us at the annual Beach Volleyball Tournament at Waddle Beach! Maximum of 7 players per team. Food and drinks included! ');
INSERT INTO events(eventname, email, eventdate, eventtime, eventlocation, latitude, longitude, eventdescription) VALUES ('Downtown Santa Cruz: Holiday Parade', 'santa@ucsc.com', '2022-12-10', '2:30:00', 'Locust Street, Santa Cruz, CA, USA', 36.9744503, -122.0307556, 'The traditional holiday parade is the official kickoff for the winter holidays celebration. One never knows exactly what to expect at the Parade, but you can be sure to expect the whole community to show up and have a great time - and of course, at the end of the parade, sitting in an antique fire truck, the man of the hour is welcomed back to Downtown Santa Cruz. Bring the family or participate! The Holiday Parade is Rain or Shine!');
INSERT INTO events(eventname, email, eventdate, eventtime, eventlocation, latitude, longitude, eventdescription) VALUES ('Ice Skating', 'iLOVEskating@gmail.com', '2022-12-10', '01:15:00', '1500 S 10th St, San Jose, CA 95112', 37.3406964, -121.8810378, 'Come join us ice skating during our public skating sessions at Sharks Ice in San Jose');
INSERT INTO events(eventname, email, eventdate, eventtime, eventlocation, latitude, longitude, eventdescription) VALUES ('Baseball and Barbeque', 'gregorysmith@gmail.com', '2023-01-12', '08:00:00', 'Camden Ave & Mt Carmel Dr, San Jose, CA 95120', 37.2204165, -121.8510282, 'Join us at the Baseball and Barbeque event located at Greystone Park! Snacks and drinks will be provided from the snackshack! Hope to see you all there!');
INSERT INTO events(eventname, email, eventdate, eventtime, eventlocation, latitude, longitude, eventdescription) VALUES ('Times Square Ball Drop!', 'newyear2023@gmail.com', '2022-12-31', '10:30:00', 'Times Square, New York, NY, USA',  40.75923, -73.9846345, 'Nothing as exhilarating as the Times Square Ball Drop! The countdown to midnight is recognized across the world as a symbol of introducing the New Year. Join us as we ring in the New Year''s in NYC');
